#!/bin/sh -eu
if [ -z "${REACT_APP_LOOKUP_SERVICE_URL:-}" ]; then
 REACT_APP_LOOKUP_SERVICE_URL_JSON=undefined
else
 REACT_APP_LOOKUP_SERVICE_URL_JSON="${REACT_APP_LOOKUP_SERVICE_URL}"
fi
if [ -z "${REACT_APP_PRODUCT_SERVICE_URL:-}" ]; then
 REACT_APP_PRODUCT_SERVICE_URL_JSON=undefined
else
 REACT_APP_PRODUCT_SERVICE_URL_JSON="${REACT_APP_PRODUCT_SERVICE_URL}"
fi
if [ -z "${REACT_APP_ACCOUNT_SERVICE_URL:-}" ]; then
 REACT_APP_ACCOUNT_SERVICE_URL_JSON=undefined
else
 REACT_APP_ACCOUNT_SERVICE_URL_JSON="${REACT_APP_ACCOUNT_SERVICE_URL}"
fi
if [ -z "${REACT_APP_APPLICATION_SERVICE_URL:-}" ]; then
 REACT_APP_APPLICATION_SERVICE_URL_JSON=undefined
else
 REACT_APP_APPLICATION_SERVICE_URL_JSON="${REACT_APP_APPLICATION_SERVICE_URL}"
fi
if [ -z "${REACT_APP_TENANT_GUID:-}" ]; then
 REACT_APP_TENANT_GUID_JSON=undefined
else
 REACT_APP_TENANT_GUID_JSON="${REACT_APP_TENANT_GUID}"
fi
if [ -z "${REACT_APP_CLIENT_ID:-}" ]; then
 REACT_APP_CLIENT_ID_JSON=undefined
else
 REACT_APP_CLIENT_ID_JSON="${REACT_APP_CLIENT_ID}"
fi
if [ -z "${REACT_APP_DOMAIN_URL:-}" ]; then
 REACT_APP_DOMAIN_URL_JSON=undefined
else
 REACT_APP_DOMAIN_URL_JSON="${REACT_APP_DOMAIN_URL}"
fi
if [ -z "${REACT_APP_TENANT_URL:-}" ]; then
 REACT_APP_TENANT_URL_JSON=undefined
else
REACT_APP_TENANT_URL_JSON="${REACT_APP_TENANT_URL}"
fi
if [ -z "${REACT_APP_B2C_POLICY:-}" ]; then
 REACT_APP_B2C_POLICY_JSON=undefined
else
 REACT_APP_B2C_POLICY_JSON="${REACT_APP_B2C_POLICY}"
fi
if [ -z "${REACT_APP_REDIRECT_PATH:-}" ]; then
 REACT_APP_REDIRECT_PATH_JSON=undefined
else
 REACT_APP_REDIRECT_PATH_JSON="${REACT_APP_REDIRECT_PATH}"
fi
if [ -z "${REACT_APP_SCOPES:-}" ]; then
 REACT_APP_SCOPES_JSON=undefined
else
 REACT_APP_SCOPES_JSON="${REACT_APP_SCOPES}"
fi
cat <<EOF
window.REACT_APP_LOOKUP_SERVICE_URL = "$REACT_APP_LOOKUP_SERVICE_URL_JSON";
window.REACT_APP_PRODUCT_SERVICE_URL = "$REACT_APP_PRODUCT_SERVICE_URL_JSON";
window.REACT_APP_ACCOUNT_SERVICE_URL = "$REACT_APP_ACCOUNT_SERVICE_URL_JSON";
window.REACT_APP_APPLICATION_SERVICE_URL = "$REACT_APP_APPLICATION_SERVICE_URL_JSON";
window.REACT_APP_TENANT_GUID = "$REACT_APP_TENANT_GUID_JSON";
window.REACT_APP_CLIENT_ID = "$REACT_APP_CLIENT_ID_JSON";
window.REACT_APP_DOMAIN_URL = "$REACT_APP_DOMAIN_URL_JSON";
window.REACT_APP_TENANT_URL = "$REACT_APP_TENANT_URL_JSON";
window.REACT_APP_B2C_POLICY = "$REACT_APP_B2C_POLICY_JSON";
window.REACT_APP_REDIRECT_PATH = "$REACT_APP_REDIRECT_PATH_JSON";
window.REACT_APP_SCOPES = "$REACT_APP_SCOPES_JSON";
EOF